project:
  type: book
  output-dir: docs

book:
  title: "Mathematics for Machine Learning"
  author: "Ryan Kingery"
  #date: "2/7/2023"
  page-navigation: true
  sidebar:
    style: docked
    background: light
  chapters:
    - index.qmd
    - notebooks/basic-math.ipynb
    - notebooks/numerical-computing.ipynb
    - notebooks/calculus.ipynb
    - notebooks/linear-systems.ipynb
    - notebooks/vector-spaces.ipynb
    - notebooks/matrix-algebra.ipynb
    - notebooks/multivariate-calculus.ipynb
    - notebooks/probability.ipynb
    #- notebooks/multivariate-probability.ipynb

#bibliography: references.bib

format:
  html:
    theme: cosmo
    page-layout: full
    toc: true
    toc-location: left
    toc-depth: 3
    #toc-title: "Section"
    number-sections: true
    code-fold: true
    fig-align: center
  # pdf:
  #   documentclass: scrreprt

jupyter: python3

