project:
  type: book

book:
  title: "Machine Learning For The 2020s"
  author: "Ryan Kingery"
  date: "2/7/2023"
  chapters:
    - index.qmd
    - notebooks/basic-math.ipynb
    - notebooks/numerical-computing.ipynb
    - notebooks/vectorization.ipynb
    - notebooks/basic-calculus.ipynb
    - notebooks/linear-systems.ipynb
    - notebooks/vector-spaces.ipynb
    - notebooks/matrix-algebra.ipynb
    - notebooks/probability.ipynb
    - notebooks/multivariate-probability.ipynb

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



