project:
  type: book
  output-dir: docs

book:
  title: "Mathematics and Computer Science for Machine Learning"
  author: "Ryan Kingery"
  page-navigation: true
  sidebar:
    style: docked
    background: light
  chapters:
    - index.qmd
    - notebooks/programming.ipynb
    - notebooks/basic-math.ipynb
    - notebooks/numerical-computing.ipynb
    - notebooks/calculus.ipynb
    - notebooks/linear-systems.ipynb
    - notebooks/vectors.ipynb
    - notebooks/matrices.ipynb
    - notebooks/tensors.ipynb
    - notebooks/multivariate-calculus.ipynb
    - notebooks/optimization.ipynb
    - notebooks/probability.ipynb
    - notebooks/multivariate-probability.ipynb
    - notebooks/statistics.ipynb

format:
  html:
    theme: cosmo
    page-layout: full
    toc: true
    toc-location: left
    toc-depth: 3
    #toc-title: "Section"
    number-sections: true
    code-fold: true
    fig-align: center
  # pdf:
  #   documentclass: scrreprt

jupyter: python3

