<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Machine Learning For The 2020s - 4&nbsp; Basic Calculus</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../notebooks/linear-systems.html" rel="next">
<link href="../notebooks/vectorization.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Basic Calculus</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Machine Learning For The 2020s</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/basic-math.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Basic Math</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/numerical-computing.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Numerical Computation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/vectorization.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Arrays and Vectorization</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/basic-calculus.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Basic Calculus</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/linear-systems.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Systems of Linear Equations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/vector-spaces.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Vector Spaces</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/matrix-algebra.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Matrix Algebra</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/multivariate-calculus.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Multivariate Calculus</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/probability.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Probability Distributions</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#infinitesimals" id="toc-infinitesimals" class="nav-link active" data-scroll-target="#infinitesimals">Infinitesimals</a></li>
  <li><a href="#limits" id="toc-limits" class="nav-link" data-scroll-target="#limits">Limits</a></li>
  <li><a href="#differentiation" id="toc-differentiation" class="nav-link" data-scroll-target="#differentiation">Differentiation</a>
  <ul class="collapse">
  <li><a href="#derivatives" id="toc-derivatives" class="nav-link" data-scroll-target="#derivatives">Derivatives</a></li>
  <li><a href="#visualizing-derivatives" id="toc-visualizing-derivatives" class="nav-link" data-scroll-target="#visualizing-derivatives">Visualizing Derivatives</a></li>
  <li><a href="#differentiation-rules" id="toc-differentiation-rules" class="nav-link" data-scroll-target="#differentiation-rules">Differentiation Rules</a></li>
  <li><a href="#application-the-sigmoid-function" id="toc-application-the-sigmoid-function" class="nav-link" data-scroll-target="#application-the-sigmoid-function">Application: The Sigmoid Function</a></li>
  </ul></li>
  <li><a href="#integration" id="toc-integration" class="nav-link" data-scroll-target="#integration">Integration</a>
  <ul class="collapse">
  <li><a href="#summing-infinitesimals" id="toc-summing-infinitesimals" class="nav-link" data-scroll-target="#summing-infinitesimals">Summing Infinitesimals</a></li>
  <li><a href="#area-under-the-curve" id="toc-area-under-the-curve" class="nav-link" data-scroll-target="#area-under-the-curve">Area Under The Curve</a></li>
  <li><a href="#integration-rules" id="toc-integration-rules" class="nav-link" data-scroll-target="#integration-rules">Integration Rules</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-body" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Basic Calculus</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>In this lesson, I’ll cover the basics of the calculus of a single variable. Calculus is essentially the study of the continuum. Important things that calculus seeks to understand are: - Infinitesimals: How to manipulate numbers that are “infinitely” small. - Limits: What happens when numbers get arbitrarily close to each other. - Differentiation: How one variable changes continuously in response to one or more other variables. - Integration: How to add up infinitely many small numbers to get a finite number.</p>
<p>Not all of these topics are equally important to know for machine learning, but I’ll try to at least touch on each topic a little bit. Let’s get started.</p>
<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sympy <span class="im">as</span> sp</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> utils.math_ml <span class="im">import</span> <span class="op">*</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>plt.rcParams[<span class="st">"figure.figsize"</span>] <span class="op">=</span> (<span class="dv">4</span>, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">'ignore'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="infinitesimals" class="level1">
<h1>Infinitesimals</h1>
<p>Fundamental to the understanding of calculus is the idea of an “infinitely small” number, called an infinitesimal. An <strong>infinitesimal</strong> is a number that’s not 0 but so close to being 0 that you can’t really tell it isn’t 0. These small numbers are often written in math with letters like <span class="math inline">\(\varepsilon\)</span> or <span class="math inline">\(\delta\)</span>. Think of them as <em>very very</em> tiny numbers, so tiny their square is basically 0: <span class="math display">\[\varepsilon &gt; 0, \quad \varepsilon^2 \approx 0.\]</span></p>
<p>But what does this even mean? Here it might be helpful to recall our discussion of floating point numbers. Recall that we can’t get infinite precision. In python’s double precision floating point we can only get down to about <span class="math inline">\(5 \cdot 10^{-324}\)</span>, or <code>5e-324</code>. If the square of a small number has a value <em>smaller</em> than about <code>5e-324</code> we’d literally get <code>0.0</code> as far as python is concerned.</p>
<p>Just for fun let’s look at the really tiny number <span class="math inline">\(10^{-300}\)</span>, or <code>1e-300</code>. That’s 300 decimal places of zeros before the 1 even shows up. Python thinks <code>1e-300</code> is just fine. But what happens if we square it? We should in theory get <span class="math inline">\(10^{-600}\)</span>, or 600 decimal places of zeros followed by a 1. But as far as floating point is concerned, the square is zero.</p>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>epsilon <span class="op">=</span> np.float64(<span class="fl">1e-300</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>epsilon, epsilon <span class="op">**</span> <span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<pre><code>(1e-300, 0.0)</code></pre>
</div>
</div>
<p>Of course, you could argue that we could just go to a higher precision then. Use more bits. But eventually, if we keep making <span class="math inline">\(\varepsilon\)</span> small enough we’ll hit a point where <span class="math inline">\(\varepsilon^2 = 0\)</span>. Thus, if it makes you feel better, when you see an infinitesimal just think “<span class="math inline">\(10^{-300}\)</span> in double precision”.</p>
<p><strong>Aside:</strong> If you want to be <em>really</em> pedantic, you might say that it shouldn’t matter what a computer does, since any positive number <span class="math inline">\(\varepsilon\)</span> squared must still be greater than zero, no matter how small <span class="math inline">\(\varepsilon\)</span> is. This is true for <em>real numbers</em> <span class="math inline">\(\mathbb{R}\)</span>. But it turns out infinitesimals aren’t real numbers at all. They lie in an extension of the real number line called the <strong>hyperreal numbers</strong>, denoted <span class="math inline">\(\mathbb{R}^*\)</span>. In my opinion, this isn’t an important distinction to worry about in applied calculus.</p>
<p>Similar to infinitesimals being numbers that can be really, really small, we can also talk about numbers being really, really big. These are called <strong>infinitely large</strong> numbers. In analogy to infinitesimals, infinitely large numbers are positive numbers <span class="math inline">\(N\)</span> whose square is basically infinite,</p>
<p><span class="math display">\[N &gt; 0, \quad N^2 \approx \infty.\]</span></p>
<p>We can get infinitely large numbers by inverting infinitesimals, and vice versa,</p>
<p><span class="math display">\[N = \frac{1}{\varepsilon}, \quad \varepsilon = \frac{1}{N}.\]</span></p>
<p>If <span class="math inline">\(10^{-300}\)</span> is a good rule of thumb for an infinitesimal, then <span class="math inline">\(10^{300}\)</span> is a good rule of thumb for an infinitely large number.</p>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>N <span class="op">=</span> np.float64(<span class="fl">1e300</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>N, N <span class="op">**</span> <span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<pre><code>(1e+300, inf)</code></pre>
</div>
</div>
<p>Infinitesimals are especially interesting when added to regular numbers. These are called <strong>first order perturbations</strong>. For example, consider some finite number <span class="math inline">\(x\)</span>. It could be <span class="math inline">\(2\)</span> or <span class="math inline">\(-100\)</span> or whatever you want. Suppose now we add to it an infinitesimal number <span class="math inline">\(\varepsilon\)</span>. Now suppose we have an output <span class="math inline">\(y\)</span> that depends on <span class="math inline">\(x\)</span> through a function <span class="math inline">\(y=f(x)=x^2\)</span>. What happens to <span class="math inline">\(y\)</span> if we perturb <span class="math inline">\(x\)</span> to <span class="math inline">\(x+\varepsilon\)</span>? That is, what is <span class="math inline">\(f(x + \varepsilon)=(x+\varepsilon)^2\)</span>? Expanding the square, we have</p>
<p><span class="math display">\[f(x + \varepsilon) = (x + \varepsilon)^2 = x^2 + 2x\varepsilon + \varepsilon^2.\]</span></p>
<p>But since <span class="math inline">\(\varepsilon^2 \approx 0\)</span>,</p>
<p><span class="math display">\[f(x + \varepsilon) = (x + \varepsilon)^2 \approx x^2 + 2x\varepsilon.\]</span></p>
<p>Okay, but what does this mean? Well, I can reformulate the question as follows: “If I change <span class="math inline">\(x\)</span> by a little bit, how much does the function <span class="math inline">\(y\)</span> change”? Call this change <span class="math inline">\(\delta\)</span>, the change in <span class="math inline">\(y\)</span> due to <span class="math inline">\(x\)</span> getting changed by <span class="math inline">\(\varepsilon\)</span>. Since <span class="math inline">\(\delta = f(x+\varepsilon) - f(x)\)</span> by definition, we’d have</p>
<p><span class="math display">\[\delta = f(x+\varepsilon) - f(x) = (x+\varepsilon)^2 - x^2 \approx 2x\varepsilon.\]</span></p>
<p>That is, if we change <span class="math inline">\(x\)</span> by a small amount <span class="math inline">\(\varepsilon\)</span>, then <span class="math inline">\(y\)</span> itself changes by a small amount <span class="math inline">\(\delta=2x\varepsilon\)</span>. Interestingly, how much <span class="math inline">\(y\)</span> changes actually depends on which <span class="math inline">\(x\)</span> we pick. If <span class="math inline">\(x=1\)</span> then <span class="math inline">\(y\)</span> changes by <span class="math inline">\(2\varepsilon\)</span>, just twice how much <span class="math inline">\(x\)</span> is nudged. If <span class="math inline">\(x=1000\)</span> though, then <span class="math inline">\(y\)</span> changes by <span class="math inline">\(2000\varepsilon\)</span>, a much bigger change, but still infinitesimal. After all, <span class="math inline">\(2000 \cdot 10^{-300} = 2 \cdot 10^{-297}\)</span> is still really, really small.</p>
</section>
<section id="limits" class="level1">
<h1>Limits</h1>
<p>One application of infinitesimals is to look at the nearby behavior of a function around some point. Suppose we have some function <span class="math inline">\(y=f(x)\)</span>. We’d like to look at the nearby behavior of the function around some point <span class="math inline">\(x=x_0\)</span>. By that, I don’t mean, what is <span class="math inline">\(f(x_0)\)</span>, I mean what is <span class="math inline">\(f(x)\)</span> when <span class="math inline">\(x\)</span> is infinitesimally close to <span class="math inline">\(x_0\)</span>.</p>
<p>Consider a first order perturbation <span class="math inline">\(x = x_0+\varepsilon\)</span> sending <span class="math inline">\(f(x_0)\)</span> to <span class="math inline">\(f(x_0+\varepsilon)\)</span>. Imagine making <span class="math inline">\(\varepsilon\)</span> smaller and smaller until it’s infinitesimal. If <span class="math inline">\(y=f(x_0+\varepsilon)\)</span> gets closer and closer to some value <span class="math inline">\(L\)</span>, we call <span class="math inline">\(L\)</span> the <strong>limit</strong> as <span class="math inline">\(x\)</span> approaches <span class="math inline">\(x_0\)</span>, and write</p>
<p><span class="math display">\[L = \lim_{x \rightarrow x_0} f(x).\]</span></p>
<p>More formally, say <span class="math inline">\(L\)</span> is the limit if the difference <span class="math inline">\(|f(x_0+\varepsilon)-L|\)</span> is infinitesimal whenever <span class="math inline">\(\varepsilon\)</span> is too. Another notation for the limit is</p>
<p><span class="math display">\[y \rightarrow L \text{ as } x \rightarrow x_0.\]</span></p>
<p>This all seems kind of pedantic if you think about it. It seems like we’re doing a bunch of extra work just to evaluate the function at <span class="math inline">\(x_0\)</span> to finally get <span class="math inline">\(L=f(x_0)\)</span>? In most cases in practice this is true, but not <em>always</em>.</p>
<p>A classic example is a function with a hole in it. Suppose we have a function <span class="math inline">\(y=f(x)\)</span> like this</p>
<p><span class="math display">\[
y =
\begin{cases}
1 &amp; x = 0, \\
x^2 &amp; x \neq 0.
\end{cases}
\]</span></p>
<p>Here’s what it looks like. It’s just a parabola <span class="math inline">\(y=x^2\)</span>, but with a hole at <span class="math inline">\(x=0\)</span> since <span class="math inline">\(f(0)=1\neq 0^2\)</span>.</p>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.arange(<span class="op">-</span><span class="dv">2</span>, <span class="dv">2</span>, <span class="fl">0.01</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>f_neq_0 <span class="op">=</span> <span class="kw">lambda</span> x: x <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>plt.plot(x, f_neq_0(x), color<span class="op">=</span><span class="st">'red'</span>, zorder<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>plt.scatter(<span class="dv">0</span>, <span class="dv">1</span>, color<span class="op">=</span><span class="st">'red'</span>, marker<span class="op">=</span><span class="st">'o'</span>, s<span class="op">=</span><span class="dv">20</span>, zorder<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>plt.scatter(<span class="dv">0</span>, <span class="dv">0</span>, c<span class="op">=</span><span class="st">'white'</span>, edgecolors<span class="op">=</span><span class="st">'red'</span>, marker<span class="op">=</span><span class="st">'o'</span>, s<span class="op">=</span><span class="dv">20</span>, zorder<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'x'</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'y'</span>)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'$y = 1$ if $x = 0$ else $x^2$'</span>)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="basic-calculus_files/figure-html/cell-6-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Suppose we make a first order perturbation to this function about <span class="math inline">\(x_0=0\)</span> by a small positive number <span class="math inline">\(\varepsilon &gt; 0\)</span>. Then</p>
<p><span class="math display">\[f(x_0+\varepsilon) = f(0 + \varepsilon) = f(\varepsilon) = \varepsilon^2.\]</span></p>
<p>If we now allow <span class="math inline">\(\varepsilon \rightarrow 0\)</span>, then clearly <span class="math inline">\(\varepsilon^2 \rightarrow 0\)</span>, so</p>
<p><span class="math display">\[L = \lim_{x \rightarrow 0} f(x) = 0 \neq f(0) = 1.\]</span></p>
<p>This is just a long drawn-out way of saying that the limit is what the function <em>would</em> be if it didn’t have a hole in it at <span class="math inline">\(x_0=0\)</span>. If the above function didn’t have a hole in it, then <span class="math inline">\(f(0)\)</span> would be <span class="math inline">\(L=0\)</span>.</p>
<p>A function that <em>is</em> well-behaved in this sense that it has no holes or jumps is called <strong>continuous</strong>. Continuous functions satisfy the very nice property that the limit can be pulled inside the function,</p>
<p><span class="math display">\[\lim_{x \rightarrow x_0} f(x) = f\bigg(\lim_{x \rightarrow x_0} x\bigg) = f(x_0).\]</span></p>
<p>Since almost every function we work with in practice is continuous, we can by and large take for granted that we can do this, keeping in mind that exceptions do occur and you sometimes have to be careful.</p>
<p>In my experience, the only real place limits seem to come up in machine learning is the infinite limit case when <span class="math inline">\(x \rightarrow \infty\)</span>,</p>
<p><span class="math display">\[\lim_{x \rightarrow \infty} f(x).\]</span></p>
<p>The easiest way to figure these limits out is to plug in a large value for <span class="math inline">\(x\)</span> and see what <span class="math inline">\(f(x)\)</span> is tending towards. For example, here’s a demonstration that</p>
<p><span class="math display">\[\lim_{x \rightarrow \infty} e^{-x} = 0.\]</span></p>
<p>You can see that <span class="math inline">\(e^{-x}\)</span> is pretty much <span class="math inline">\(0\)</span> by the time <span class="math inline">\(x=20\)</span>, which suggests the limit is <span class="math inline">\(0\)</span> as <span class="math inline">\(x \rightarrow \infty\)</span>. While this isn’t a “proof”, it should be pretty convincing.</p>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> x <span class="kw">in</span> np.exp(<span class="bu">range</span>(<span class="dv">6</span>)):</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> np.exp(<span class="op">-</span>x)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'x = </span><span class="sc">{</span>x<span class="sc">.</span><span class="bu">round</span>(<span class="dv">2</span>)<span class="sc">}</span><span class="ss"> </span><span class="ch">\t</span><span class="ss"> y = </span><span class="sc">{</span>y<span class="sc">.</span><span class="bu">round</span>(<span class="dv">8</span>)<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x = 1.0      y = 0.36787944
x = 2.72     y = 0.06598804
x = 7.39     y = 0.00061798
x = 20.09    y = 0.0
x = 54.6     y = 0.0
x = 148.41   y = 0.0</code></pre>
</div>
</div>
<p>If you like, you can also use sympy to evaluate the infinite limit symbolically.</p>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> sp.symbols(<span class="st">'x'</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> sp.exp(<span class="op">-</span>x)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>sp.limit(y, x, sp.oo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<p><span class="math inline">\(\displaystyle 0\)</span></p>
</div>
</div>
<p>Generally speaking, each additive term in a function will go like its most dominating component as <span class="math inline">\(x \rightarrow \infty\)</span>. For example, take the continuous function <span class="math inline">\(y=x e^{-x} + 1\)</span>. The first term <span class="math inline">\(xe^{-x}\)</span> is dominated by <span class="math inline">\(e^{-x}\)</span> when <span class="math inline">\(x\)</span> is large, since it shrinks to <span class="math inline">\(0\)</span> <em>much</em> faster than <span class="math inline">\(x\)</span> increases. Since the other term just stays at <span class="math inline">\(1\)</span>, we get</p>
<p><span class="math display">\[\lim_{x \rightarrow \infty} (x e^{-x} + 1) = 0 + 1 = 1.\]</span></p>
<p>When <span class="math inline">\(x\)</span> gets large, the following rule of thumb holds for different classes of functions, with functions to the left dominating functions to the right,</p>
<p><span class="math display">\[\text{factorials} &gt;&gt; \text{exponents} &gt;&gt; \text{polynomials} &gt;&gt; \text{logarithms} &gt;&gt; \text{constants}.\]</span></p>
<p>If you’ll recall, this exact same chain was shown when I talked about asymptotic notation. In fact, we can use infinite limits to formally define what big-oh notation means. Say a function <span class="math inline">\(f(x)\)</span> is <span class="math inline">\(O(g(x))\)</span> if</p>
<p><span class="math display">\[\lim_{n \rightarrow \infty} \bigg|\frac{f(n)}{g(n)}\bigg| \leq M\]</span></p>
<p>for some finite constant <span class="math inline">\(M &gt; 0\)</span>. For example, the function <span class="math inline">\(f(n) = n^3 + 2n^2 - 5n\)</span> is <span class="math inline">\(O(n^3)\)</span> since</p>
<p><span class="math display">\[\lim_{n \rightarrow \infty} \bigg|\frac{n^3 + 2n^2 - 5n}{n^3}\bigg| =  \lim_{n \rightarrow \infty} \bigg(1 + \frac{2}{n} - \frac{5}{n^2}\bigg) = 1 \leq 1.\]</span></p>
</section>
<section id="differentiation" class="level1">
<h1>Differentiation</h1>
<section id="derivatives" class="level2">
<h2 class="anchored" data-anchor-id="derivatives">Derivatives</h2>
<p>Let’s go back to our example before where we looked at first order perturbations to the function <span class="math inline">\(y=x^2\)</span>. We showed if <span class="math inline">\(x\)</span> is infinitesimally changed to <span class="math inline">\(x + \varepsilon\)</span>, then <span class="math inline">\(y\)</span> is changed to <span class="math inline">\(y + \delta \approx 2x\varepsilon\)</span>.</p>
<p>When we talk about changing <span class="math inline">\(x\)</span> by a little bit and asking how <span class="math inline">\(y\)</span> changes we use a cleaner notation. Instead of writing <span class="math inline">\(x + \varepsilon\)</span>, we’d write <span class="math inline">\(x + dx\)</span>. Instead of writing <span class="math inline">\(y + \delta\)</span>, we’d write <span class="math inline">\(y + dy\)</span>. These values <span class="math inline">\(dx\)</span> and <span class="math inline">\(dy\)</span> are called <strong>differentials</strong>.</p>
<p>They’re just infinitesimals like I defined them before, but this differential notation makes it clear what is a small change of what. Writing <span class="math inline">\(dx\)</span> means “a little bit of <span class="math inline">\(x\)</span>”. Writing <span class="math inline">\(dy\)</span> means “a little bit of <span class="math inline">\(y\)</span>”. This is where the term “differentiation” comes from.</p>
<p>In the language of differentials, we want to ask what happens to <span class="math inline">\(y+dy\)</span> in response to perturbations <span class="math inline">\(x+dx\)</span>. In our running example, this is</p>
<p><span class="math display">\[y + dy = f(x+dx) = (x + dx)^2 = x^2 + 2xdx + dx^2 \approx x^2 + 2xdx,\]</span></p>
<p>with the approximate equality becoming exact when <span class="math inline">\(dx\)</span> is infinitesimal.</p>
<p>Let’s solve for <span class="math inline">\(dy\)</span>, how much <span class="math inline">\(y\)</span> changes in response to <span class="math inline">\(x\)</span> changing a little bit. Subtracting both sides by <span class="math inline">\(y=x^2\)</span> just gives <span class="math inline">\(dy = 2xdx\)</span>. If we then divide both sides by <span class="math inline">\(dx\)</span> we get <span class="math display">\[\frac{dy}{dx} = 2x.\]</span></p>
<p>This ratio of differentials <span class="math inline">\(\frac{dy}{dx}\)</span> is called the <strong>derivative</strong> of the function <span class="math inline">\(y=x^2\)</span>, usually just pronounced “dydx”. The act of taking a derivative is called <strong>differentiation</strong>. Notice there’s no infinitesimal (<span class="math inline">\(dy\)</span> or <span class="math inline">\(dx\)</span>) on the right-hand side, hence the derivative is not itself an infinitesimal. It’s finite.</p>
<p>Notice that the derivative is a <em>function</em> since it maps inputs <span class="math inline">\(x\)</span> to outputs <span class="math inline">\(\frac{dy}{dx}=2x\)</span>. To indicate this functional relationship people sometimes write either</p>
<p><span class="math display">\[\frac{dy}{dx}=\frac{d}{dx}f(x) \quad \text{ or } \quad \frac{dy}{dx}=f'(x)\]</span> to make this clear.</p>
<p>Let’s use python to try to calculate what the derivative of <span class="math inline">\(y=x^2\)</span> is for a specific value of <span class="math inline">\(x\)</span>, say <span class="math inline">\(x=1\)</span>. We can do this by taking smaller and smaller values of <span class="math inline">\(dx\)</span> and looking at the ratio <span class="math display">\[\frac{dy}{dx}\bigg|_{x=1} = \frac{(x+dx)^2 - x^2}{dx}\]</span> for different choices of <span class="math inline">\(dx\)</span>.</p>
<p><strong>Notation:</strong> Read the left-hand side of this expression as “the derivative evaluated at <span class="math inline">\(x=1\)</span>”. Another way to write the same thing is <span class="math inline">\(f'(1)\)</span> or <span class="math inline">\(\frac{d}{dx}f(1)\)</span>.</p>
<p>I’ll define a loop over some values of <span class="math inline">\(dx\)</span> and see what the predicted derivative is. Since the exact derivative function is <span class="math inline">\(2x\)</span>, the exact answer at <span class="math inline">\(x=1\)</span> should be <span class="math display">\[\frac{dy}{dx}\bigg|_{x=1} = 2 \cdot 1 = 2.\]</span></p>
<p>I’ll also print out the error, which is the predicted value <span class="math inline">\(2\)</span> minus the calculated value. Smaller error is better, obviously.</p>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>f <span class="op">=</span> <span class="kw">lambda</span> x: x <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>x0 <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>dydx_exact <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> x0</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> dx <span class="kw">in</span> [<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="fl">0.01</span>, <span class="fl">0.001</span>, <span class="fl">1e-4</span>, <span class="fl">1e-5</span>, <span class="fl">1e-10</span>, <span class="fl">1e-100</span>, <span class="fl">1e-200</span>]:</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    dydx <span class="op">=</span> (f(x0 <span class="op">+</span> dx) <span class="op">-</span> f(x0)) <span class="op">/</span> dx</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    error <span class="op">=</span> dydx <span class="op">-</span> dydx_exact</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'dx = </span><span class="sc">{</span>dx<span class="sc">:8.16f}</span><span class="ss"> </span><span class="ch">\t</span><span class="ss"> dy/dx = </span><span class="sc">{</span>dydx<span class="sc">:4f}</span><span class="ss"> </span><span class="ch">\t</span><span class="ss"> error = </span><span class="sc">{</span>error<span class="sc">:4f}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>dx = 1.0000000000000000      dy/dx = 3.000000    error = 1.000000
dx = 0.1000000000000000      dy/dx = 2.100000    error = 0.100000
dx = 0.0100000000000000      dy/dx = 2.010000    error = 0.010000
dx = 0.0010000000000000      dy/dx = 2.001000    error = 0.001000
dx = 0.0001000000000000      dy/dx = 2.000100    error = 0.000100
dx = 0.0000100000000000      dy/dx = 2.000010    error = 0.000010
dx = 0.0000000001000000      dy/dx = 2.000000    error = 0.000000
dx = 0.0000000000000000      dy/dx = 0.000000    error = -2.000000
dx = 0.0000000000000000      dy/dx = 0.000000    error = -2.000000</code></pre>
</div>
</div>
<p>Starting with <span class="math inline">\(dx=1\)</span> is a bad choice, with a huge error of <span class="math inline">\(1.0\)</span>. We’re way off. Shrinking to <span class="math inline">\(dx=0.1\)</span> puts us in the ball park with a value <span class="math inline">\(\frac{dy}{dx}=2.1\)</span>. You can see that making <span class="math inline">\(dx\)</span> successively smaller and smaller makes the error successively smaller, in this case by a factor of 10 each time.</p>
<p>The error is getting smaller all the way down to about <span class="math inline">\(dx=10^{-10}\)</span> before creeping up again as we make <span class="math inline">\(dx\)</span> even smaller than that. This is due to the numerical roundoff of floating point numbers. We’re subtracting two numbers <span class="math inline">\(f(x_0+dx) - f(x_0) = (1+dx)^2 - 1\)</span> that are very close to each other when <span class="math inline">\(dx\)</span> is really small, which as you’ll recall is one of the pitfalls to avoid when working with floating point numbers.</p>
<p>This method we just used to calculate the derivative is essentially exactly how derivatives are usually calculated on a computer. The process of calculating the derivative this way, directly from its definition essentially, is called <strong>numerical differentiation</strong>. We choose a small value of <span class="math inline">\(dx\)</span> and just apply the formula above, with some minor tweaks to get better accuracy in fewer steps. It’s common in practice to choose “less small” values for <span class="math inline">\(dx\)</span> when calculating derivatives numerically like this, e.g.&nbsp;<code>1e-5</code>.</p>
<p>We can talk about any reasonably well-behaved function <span class="math inline">\(f(x)\)</span> having a derivative. If <span class="math inline">\(y=f(x)\)</span> and we make a first order perturbation <span class="math inline">\(x+dx\)</span>, then <span class="math inline">\(y\)</span> gets perturbed by <span class="math inline">\(y+dy=f(x+dx)\)</span>. The amount <span class="math inline">\(y=f(x)\)</span> changes <em>per amount</em> <span class="math inline">\(dx\)</span> is then the <strong>derivative</strong></p>
<p><span class="math display">\[\frac{dy}{dx} = \frac{f(x+dx)-f(x)}{dx}.\]</span></p>
<p>This definition is only exact when <span class="math inline">\(dx\)</span> is infinitesimal. For finite values of <span class="math inline">\(dx\)</span> (like what we’d code up on a computer) this equality is only approximately true.</p>
<p>What do I mean when I say the function <span class="math inline">\(f(x)\)</span> needs to be reasonably well behaved? For one thing, the function needs to be <strong>continuous</strong>. Informally, you can think of a univariate function as being continuous if you can draw its graph on a piece of paper without lifting your pen. There are no jumps or holes anywhere in the functions’ curve. More formally, a function is continuous at <span class="math inline">\(x_0\)</span> if <span class="math inline">\(f(x) \rightarrow f(x_0)\)</span> as <span class="math inline">\(x \rightarrow x_0\)</span>. That is, all the limits are what they should be. There are no holes or jumps in the graph.</p>
<p>Continuity is just <em>one</em> condition necessary for <span class="math inline">\(f(x)\)</span> to be differentiable. It also can’t be too jagged in some sense. Derivatives don’t make sense at points where there are kinks in the function curve. At points where there are kinks we have to use a slightly different kind of derivative called a <a href="https://en.wikipedia.org/wiki/Subderivative">subderivative</a>.</p>
<p>Since derivatives are functions we can take the derivative of the derivative too, <span class="math inline">\(\frac{d}{dx} \frac{dy}{dx}\)</span>, which turns out to be</p>
<p><span class="math display">\[\frac{d^2 y}{dx^2} = \frac{d}{dx} \frac{dy}{dx} = \frac{d}{dx} \frac{f(x+dx)-f(x)}{dx} = \frac{f(x+2dx) - 2f(x+dx) + f(x)}{dx^2}.\]</span></p>
<p>This is called a <strong>second derivative</strong>, and sometimes also written <span class="math inline">\(f'(x)\)</span> or <span class="math inline">\(\frac{d^2}{dx^2} f(x)\)</span>.</p>
<p>As a quick example, the second derivative of our running function <span class="math inline">\(y=x^2\)</span> is the first derivative of <span class="math inline">\(2x\)</span>, which is</p>
<p><span class="math display">\[\frac{d^2 y}{dx^2} = \frac{2(x + dx) - 2x}{dx} = 2.\]</span></p>
<p>Higher-order derivatives can be defined as well by continuing to take derivatives of the second derivative, like third derivatives of fourth derivatives. These show up less prominently though, and as such aren’t discussed all that much.</p>
</section>
<section id="visualizing-derivatives" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-derivatives">Visualizing Derivatives</h2>
<p>The first derivative <span class="math inline">\(\frac{dy}{dx}\)</span> has an interesting and useful geometric interpretation as the <strong>slope</strong> of the curve <span class="math inline">\(y=f(x)\)</span> at the point <span class="math inline">\(x\)</span>. To see this, imagine a right triangle with length <span class="math inline">\(dx\)</span> and height <span class="math inline">\(dy\)</span>. The slope, or “steepness”, of its hypotenuse is just the ratio height over width, i.e.&nbsp;<span class="math inline">\(\frac{dy}{dx}\)</span>.</p>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>plot_right_triangle()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="basic-calculus_files/figure-html/cell-10-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>We can use this idea to talk about the slope of a function at a point. If <span class="math inline">\(y=f(x)\)</span> is a function, then the derivative <span class="math inline">\(\frac{dy}{dx}\)</span> at some point <span class="math inline">\(x=x_0\)</span> is the slope of that function at the point <span class="math inline">\((x_0,y_0)\)</span>. It’s the slope of the line that hugs the point <span class="math inline">\((x_0,y_0)\)</span> <em>tangent</em> to the curve. This “hugging line” is called the <strong>tangent line</strong>. We can pretty easily solve for what this line has to be. It must run through <span class="math inline">\((x_0,y_0)\)</span> and have slope <span class="math inline">\(m=\frac{d}{dx}f(x_0)\)</span>, so writing <span class="math inline">\(y=mx+b\)</span> and solving for the intercept <span class="math inline">\(b\)</span> would give the first order perturbation</p>
<p><span class="math display">\[y = y_0 + \frac{d}{dx}f(x_0)(x - x_0).\]</span></p>
<p>Here’s an example. I’ll plot the function <span class="math inline">\(y=x^2\)</span> and its <em>tangent</em> at a point <span class="math inline">\(x_0=2\)</span> on the x-axis. The corresponding <span class="math inline">\(y\)</span> at <span class="math inline">\(x=2\)</span> is just <span class="math inline">\(y_0=x_0^2=4\)</span>. As we derived above, its derivative (and hence slope) at <span class="math inline">\(x_0=2\)</span> is</p>
<p><span class="math display">\[\frac{d}{dx}f(2)=2(2)=4,\]</span></p>
<p>so the equation for the tangent line of <span class="math inline">\(y=x^2\)</span> at <span class="math inline">\(x_0=2\)</span> is</p>
<p><span class="math display">\[y = 4 + 4(x - 2) = 4x -4.\]</span></p>
<p>The code below implements this calculation. I’ll define the function <code>f</code> that gives <code>y = f(x)</code> along with the derivative <code>dydx = dfdx(x)</code>, and then use these two define a function <code>f_line</code> to calculate the tangent line, which also depends on a specified point <code>x0</code>.</p>
<p>Feel free to adjust the value of <code>x0</code> observe how the slope changes with the value you pick. In all cases, the line should hug the curve of the function and stay tangent to it.</p>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>f <span class="op">=</span> <span class="kw">lambda</span> x: x <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>dfdx <span class="op">=</span> <span class="kw">lambda</span> x: <span class="dv">2</span> <span class="op">*</span> x</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>x0 <span class="op">=</span> <span class="dv">2</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.arange(<span class="op">-</span><span class="dv">3</span> <span class="op">*</span> x0, <span class="dv">3</span> <span class="op">*</span> x0, <span class="fl">0.1</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>f_line <span class="op">=</span> <span class="kw">lambda</span> x: f(x0) <span class="op">+</span> dfdx(x0) <span class="op">*</span> (x <span class="op">-</span> x0)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>plot_tangent_curve(x, x0, f, f_line, xlim<span class="op">=</span>(<span class="op">-</span><span class="dv">5</span>, <span class="dv">5</span>), ylim<span class="op">=</span>(<span class="dv">0</span>, <span class="dv">10</span>), </span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>                   title<span class="op">=</span><span class="ss">f'Tangent Line of $y=x^2$ at $</span><span class="sc">{</span>(x0, f(x0))<span class="sc">}</span><span class="ss">$'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="basic-calculus_files/figure-html/cell-11-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Generally speaking, if the derivative <span class="math inline">\(\frac{dy}{dx}\)</span> at a point is <em>positive</em> the tangent line will slant towards the <em>right</em>. If the derivative at that point is <em>negative</em> the tangent line will slant towards the <em>left</em>. If it’s zero, the tangent line there will be horizontal.</p>
<p>The second derivative <span class="math inline">\(\frac{d^2 y}{dx^2}\)</span> has a geometric interpretation as well. It captures information about the <em>curvature</em> of the function. To see why this is true we need to look at <em>second order perturbations</em>. That is, we need to add in a term to the tangent line equation of order <span class="math inline">\((x-x_0)^2\)</span>,</p>
<p><span class="math display">\[y = f(x_0) + \frac{d}{dx}f(x_0) (x-x_0) + \color{red}{\frac{1}{2}\frac{d^2}{dx^2}f(x_0) (x-x_0)^2}.\]</span></p>
<p>What may seem weird is the <span class="math inline">\(\frac{1}{2}\)</span> out front of the red second-order term. This has to do with how Taylor series work, a topic I don’t see a need to cover at the moment. What’s important though is the term is quadratic, and it depends on the second derivative at <span class="math inline">\(x=x_0\)</span>.</p>
<p>A second order perturbation defines a <em>tangent parabola</em> given by a quadratic function <span class="math inline">\(y=ax^2+bx+c\)</span>, where <span class="math inline">\(a,b,c\)</span> are coefficients determined by the values of the inputs <span class="math inline">\(f(x_0), \frac{d}{dx}f(x_0), \frac{d^2}{dx^2}f(x_0)\)</span>. Most importantly, the leading coefficient <span class="math inline">\(a\)</span> is just the second derivative at <span class="math inline">\(x=x_0\)</span>, i.e.&nbsp;<span class="math inline">\(a = \frac{d^2}{dx^2}f(x_0)\)</span>.</p>
<p>Since <span class="math inline">\(a\)</span> determines the shape of the tangent parabola, it also determines the curvature of the function at <span class="math inline">\(x=x_0\)</span>. If <span class="math inline">\(a\)</span> is large at <span class="math inline">\(x=x_0\)</span>, the function will be sharply curved around that point. If <span class="math inline">\(a\)</span> is small, the function will be very flat around <span class="math inline">\(x=x_0\)</span>. The sign of <span class="math inline">\(a\)</span> will indicate whether the function is curved upward or downward. If <span class="math inline">\(a&gt;0\)</span> the function will be curved upward. If <span class="math inline">\(a &lt; 0\)</span> it’ll curve downward.</p>
<p>In our example <span class="math inline">\(y=x^2\)</span>, since <span class="math inline">\(a=\frac{d^2 y}{dx^2} = 2 &gt; 0\)</span>, meaning the tangent parabola is just the function <span class="math inline">\(y=x^2\)</span> itself. Of course it is. Since <span class="math inline">\(a\)</span> is constant, the curvature for the parabola is the same everywhere.</p>
<p>Since <span class="math inline">\(a=2&gt;0\)</span>, the function <span class="math inline">\(y=x^2\)</span> “bowls upward” everywhere. Functions that “bowl upward” everywhere like this are called <strong>convex function</strong>. If instead <span class="math inline">\(a &lt; 0\)</span> everywhere, e.g.&nbsp;like it would be for <span class="math inline">\(y=-x^2\)</span>, the function would “bowl downward” everywhere. These are called <strong>convave functions</strong>. Convex (and concave) functions are very important for machine learning and optimization more generally since they’re guaranteed to have a unique global minimum (or maximum). More on this in a future lesson.</p>
<p>Here’s a more general example where the second derivative isn’t constant, <span class="math inline">\(y = \sin x\)</span>. In this case, <span class="math inline">\(\frac{dy}{dx} = \cos x\)</span> and <span class="math inline">\(\frac{d^2y}{dx^2} = -\sin x\)</span>. Suppose we want to get the tangent parabola at the point <span class="math inline">\(x_0=-\frac{\pi}{2}\)</span>, so <span class="math inline">\(f(x_0)=-1\)</span>, <span class="math inline">\(\frac{d}{dx}f(x_0)=0\)</span> and <span class="math inline">\(\frac{d^2}{dx^2}f(x_0)=1\)</span>. Then the tangent parabola is given by the equation</p>
<p><span class="math display">\[y = -1 + 0 \cdot \bigg(x + \frac{\pi}{2}\bigg) + \bigg(x + \frac{\pi}{2}\bigg)^2.\]</span></p>
<p>This is an upward-sloping parabola with vertex at <span class="math inline">\(\big(\frac{\pi}{2}, -1\big)\)</span>. Here’s a plot of this idea using the same helper function, but passing in <code>f_parabola</code> instead of <code>f_tangent</code>. Notice how the parabola approximates the function pretty well around the point <span class="math inline">\(\big(\frac{\pi}{2}, -1\big)\)</span>, but gets less and less accurate as we get away from that point. The fact that <span class="math inline">\(a=1\)</span> here says that we should expect an upward sloping parabola with “unit curvature”, which is what we see.</p>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>f <span class="op">=</span> <span class="kw">lambda</span> x: np.sin(x)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>dfdx <span class="op">=</span> <span class="kw">lambda</span> x: np.cos(x)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>d2fdx2 <span class="op">=</span> <span class="kw">lambda</span> x: <span class="op">-</span>np.sin(x)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>x0 <span class="op">=</span> <span class="op">-</span>np.pi <span class="op">/</span> <span class="dv">2</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.arange(<span class="op">-</span><span class="dv">5</span>, <span class="dv">5</span>, <span class="fl">0.1</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>f_parabola <span class="op">=</span> <span class="kw">lambda</span> x: f(x0) <span class="op">+</span> dfdx(x0) <span class="op">*</span> (x <span class="op">-</span> x0) <span class="op">+</span> <span class="dv">1</span><span class="op">/</span><span class="dv">2</span> <span class="op">*</span> d2fdx2(x0) <span class="op">*</span> (x <span class="op">-</span> x0) <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>plot_tangent_curve(x, x0, f, f_parabola, xlim<span class="op">=</span>(<span class="op">-</span><span class="dv">5</span>, <span class="dv">5</span>), ylim<span class="op">=</span>(<span class="op">-</span><span class="fl">1.5</span>, <span class="fl">1.5</span>), </span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>                   title<span class="op">=</span><span class="ss">f'Tangent Parabola of $y=\sin x$ at $(\pi/2, -1)$'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="basic-calculus_files/figure-html/cell-12-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="differentiation-rules" class="level2">
<h2 class="anchored" data-anchor-id="differentiation-rules">Differentiation Rules</h2>
<p>As we’ve seen, derivatives are also functions in and of themselves, mapping inputs to outputs via <span class="math inline">\(\frac{dy}{dx} = \frac{d}{dx}f(x)\)</span>. For this reason, several rules exist relating derivatives to their original functions.</p>
<p>Here are the derivatives of some common functions that come up:</p>
<table class="table">
<thead>
<tr class="header">
<th>Function</th>
<th>Derivative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\frac{d}{dx}1\)</span></td>
<td><span class="math inline">\(0\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\frac{d}{dx}0\)</span></td>
<td><span class="math inline">\(0\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\frac{d}{dx}x\)</span></td>
<td><span class="math inline">\(1\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\frac{d}{dx}x^2\)</span></td>
<td><span class="math inline">\(2x\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\frac{d}{dx}\sqrt{x}\)</span></td>
<td><span class="math inline">\(\frac{1}{2\sqrt{x}}\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\frac{d}{dx}\frac{1}{x}\)</span></td>
<td><span class="math inline">\(-\frac{1}{x^2}\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\frac{d}{dx}e^x\)</span></td>
<td><span class="math inline">\(e^x\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\frac{d}{dx}\log{x}\)</span></td>
<td><span class="math inline">\(\frac{1}{x}\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\frac{d}{dx}\sin{x}\)</span></td>
<td><span class="math inline">\(\cos{x}\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\frac{d}{dx}\cos{x}\)</span></td>
<td><span class="math inline">\(-\sin{x}\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\frac{d}{dx}\sigma(x)\)</span></td>
<td><span class="math inline">\(\sigma(x)\big(1-\sigma(x)\big)\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\frac{d}{dx}\tanh(x)\)</span></td>
<td><span class="math inline">\(\big(1 - \tanh^2(x)\big)\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\frac{d}{dx}\text{ReLU}(x)\)</span></td>
<td><span class="math inline">\(u(x) = [x \geq 0]\)</span></td>
</tr>
</tbody>
</table>
<p>Here are some more general derivative rules you can use to differentiate more arbitrary functions:</p>
<table class="table">
<colgroup>
<col style="width: 7%">
<col style="width: 24%">
<col style="width: 69%">
</colgroup>
<thead>
<tr class="header">
<th>Name</th>
<th>Rule</th>
<th>Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td><span class="math inline">\(\frac{d}{dx}(c) = 0\)</span> for any constant <span class="math inline">\(c\)</span></td>
<td><span class="math inline">\(\frac{d}{dx}(10) = 0\)</span></td>
</tr>
<tr class="even">
<td>Power Rule</td>
<td><span class="math inline">\(\frac{d}{dx}x^n = nx^{n-1}\)</span> for any <span class="math inline">\(n \neq 0\)</span></td>
<td><span class="math inline">\(\frac{d}{dx}x^3 = 3x^2\)</span></td>
</tr>
<tr class="odd">
<td>Addition Rule</td>
<td><span class="math inline">\(\frac{d}{dx}(u + v) = \frac{du}{dx} + \frac{dv}{dx}\)</span></td>
<td><span class="math inline">\(\frac{d}{dx}(x^2 + \log x) = \frac{d}{dx}x^2 + \frac{d}{dx}\log x = 2x + \frac{1}{x}\)</span></td>
</tr>
<tr class="even">
<td>Constant Rule</td>
<td><span class="math inline">\(\frac{d}{dx}(cy) = c \frac{dy}{dx}\)</span> for any constant <span class="math inline">\(c\)</span></td>
<td><span class="math inline">\(\frac{d}{dx}2 \sin x = 2 \frac{d}{dx}\sin x = 2 \cos x\)</span></td>
</tr>
<tr class="odd">
<td>Product Rule</td>
<td><span class="math inline">\(\frac{d}{dx}(uv)=u\frac{dv}{dx} + v\frac{du}{dx}\)</span></td>
<td><span class="math inline">\(\frac{d}{dx}(x e^x) = x \frac{d}{dx}e^x + e^x \frac{d}{dx} x = xe^x + e^x\)</span></td>
</tr>
<tr class="even">
<td>Quotient Rule</td>
<td><span class="math inline">\(\frac{d}{dx}\big(\frac{u}{v}\big) = \frac{v\frac{du}{dx}-u\frac{dv}{dx}}{v^2}\)</span></td>
<td><span class="math inline">\(\frac{d}{dx} \frac{\cos x}{x^2} = \frac{x^2\frac{d}{dx}\cos x-\cos x\frac{d}{dx}x^2}{(x^2)^2} = \frac{-x^2 \sin x - 2x \cos x}{x^4}\)</span></td>
</tr>
<tr class="odd">
<td>Chain Rule</td>
<td><span class="math inline">\(\frac{d}{dx}f(g(x)) = \frac{d}{dy}f(y)\frac{d}{dx}g(x) = \frac{dz}{dy}\frac{dy}{dx}\)</span></td>
<td><span class="math inline">\(\frac{d}{dx} e^{\sin x} = \frac{d}{dy} e^y \frac{d}{dx}\sin x = e^{\sin x} \cos x\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Aside:</strong> These rules are simple to derive using infinitesimals. For example, here’s a derivation of the all important chain rule. Suppose we have a composite function of two differentiable functions <span class="math inline">\(z=f(y)\)</span> and <span class="math inline">\(y=g(x)\)</span>. That is, <span class="math inline">\(z=f(g(x))\)</span>. Perturb <span class="math inline">\(x\)</span> by some infinitesimal <span class="math inline">\(dx\)</span>. Then <span class="math inline">\(y + dy = g(x + dx)\)</span>, so</p>
<p><span class="math display">\[dy = g(x+dx)-g(x) = \frac{g(x+dx)-g(x)}{dx} dx = \frac{dy}{dx} dx.\]</span></p>
<p>Since <span class="math inline">\(dy\)</span> is also infinitesimal, perturbing <span class="math inline">\(y\)</span> by <span class="math inline">\(dy\)</span> will do the same thing to <span class="math inline">\(z=f(y)\)</span>, since <span class="math inline">\(z + dz = f(y + dy)\)</span>, and</p>
<p><span class="math display">\[dz = f(y+dy)-f(y) = \frac{f(y+dy)-f(y)}{dy} dy = \frac{dz}{dy} dy,\]</span></p>
<p>Putting these two results together, the infinitesimal change <span class="math inline">\(dz\)</span> in <span class="math inline">\(z=f(g(x))\)</span> resulting from the original infinitesimal change <span class="math inline">\(dx\)</span> is given by</p>
<p><span class="math display">\[dz = \frac{dz}{dy} dy = \frac{dz}{dy} \frac{dy}{dx} dx.\]</span></p>
<p>Dividing both sides by <span class="math inline">\(dx\)</span> gives the derivative of the composite function <span class="math inline">\(z=f(g(x))\)</span>,</p>
<p><span class="math display">\[\frac{dz}{dx} = \frac{dz}{dy}\frac{dy}{dx}. \square\]</span></p>
</section>
<section id="application-the-sigmoid-function" class="level2">
<h2 class="anchored" data-anchor-id="application-the-sigmoid-function">Application: The Sigmoid Function</h2>
<p>To illustrate how to calculate derivatives I’ll use a relevant example to machine learning, the sigmoid function. Recall the sigmoid function <span class="math inline">\(y=\sigma(x)\)</span> is defined by</p>
<p><span class="math display">\[y = \frac{1}{1 + e^{-x}}.\]</span></p>
<p>Its shape looks like an S (hence the name), going from <span class="math inline">\(y=0\)</span> at <span class="math inline">\(x=-\infty\)</span> to <span class="math inline">\(y=1\)</span> at <span class="math inline">\(x=\infty\)</span>.</p>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.arange(<span class="op">-</span><span class="dv">10</span>, <span class="dv">10</span>, <span class="fl">0.1</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>f <span class="op">=</span> <span class="kw">lambda</span> x:  <span class="dv">1</span> <span class="op">/</span> (<span class="dv">1</span> <span class="op">+</span> np.exp(<span class="op">-</span>x))</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>plot_function(x, f, xlim<span class="op">=</span>(<span class="op">-</span><span class="dv">10</span>, <span class="dv">10</span>), ylim<span class="op">=</span>(<span class="op">-</span><span class="fl">0.5</span>, <span class="fl">1.5</span>), ticks_every<span class="op">=</span>[<span class="dv">5</span>, <span class="fl">0.5</span>], title<span class="op">=</span><span class="st">'Sigmoid Function'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="basic-calculus_files/figure-html/cell-13-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Let’s calculate the derivative of this function. First, though, let’s use some intuition and try to figure out what the derivative should be doing based on the shape of the sigmoid curve. When <span class="math inline">\(x\)</span> is really negative, say <span class="math inline">\(x &lt; -5\)</span>, the slope looks basically flat, hence the derivative should be zero there. Similarly, when <span class="math inline">\(x\)</span> is really positive, say <span class="math inline">\(x &gt; 5\)</span>, the derivative should be zero there too. Around <span class="math inline">\(x=0\)</span>, say <span class="math inline">\(-1 &lt; x &lt; 1\)</span>, the sigmoid looks kind of linear with positive slope. There we should expect the derivative to be positive, and roughly constant over that interval.</p>
<p>To verify this, let’s calculate the derivative of the sigmoid explicitly. There are a few ways to do this, but I’ll use the chain rule here. We have</p>
<p><span class="math display">\[\begin{align}
\frac{d}{dx} \sigma(x) &amp;= \frac{d}{dx} \frac{1}{1 + e^{-x}}\\
&amp;= \frac{d}{dx} (1 + e^{-x})^{-1} \\
&amp;= (-1) (1 + e^{-x})^{-2} \frac{d}{dx} e^{-x} \\
&amp;= -(1 + e^{-x})^{-2} (-1) e^{-x} \\
&amp;= \frac{e^{-x}}{(1 + e^{-x})^{2}} \\
&amp;= \frac{1}{1 + e^{-x}} \frac{(1 + e^{-x}) - 1}{1 + e^{-x}} \\
&amp;= \frac{1}{1 + e^{-x}} \bigg(1-\frac{1}{1 + e^{-x}}\bigg) \\
&amp;= \sigma(x) \big(1 - \sigma(x)\big).
\end{align}\]</span></p>
<p>Let’s look at this answer and verify it matches our intuition as to what the derivative of the sigmoid should be. - When <span class="math inline">\(x &lt; -5\)</span>, <span class="math inline">\(\sigma(x) \approx 0\)</span>, hence <span class="math inline">\(\frac{d}{dx} \sigma(x) \approx 0\)</span>. - When <span class="math inline">\(x &gt; 5\)</span>, <span class="math inline">\(\sigma(x) \approx 1\)</span>, so <span class="math inline">\(1 - \sigma(x) \approx 0\)</span>, and again <span class="math inline">\(\frac{d}{dx} \sigma(x) \approx 0\)</span>. - When <span class="math inline">\(-1 &lt; x &lt; 1\)</span>, <span class="math inline">\(\sigma(x) \approx \sigma(0) + \frac{d}{dx}\sigma(0) \cdot (x-0) = \frac{1}{2} + \frac{1}{2}\big(1 - \frac{1}{2}\big) \cdot x = \frac{1}{2} + \frac{1}{4}x\)</span>, which is a tangent line with a positive slope of <span class="math inline">\(\frac{1}{4}\)</span>.</p>
<p>To further verify the things look like a line around <span class="math inline">\(x=0\)</span>, we could look at the second derivative and verify it’s approximately zero in the region <span class="math inline">\(-1 &lt; x &lt; 1\)</span>. I’ll leave that exercise to you.</p>
<p>The sigmoid function shows up in machine learning when doing binary classification. If a problem can be classified into two classes, <span class="math inline">\(0\)</span> or <span class="math inline">\(1\)</span>, the sigmoid can be used to model the probability of the input being in class <span class="math inline">\(1\)</span>. The closer the sigmoid is to <span class="math inline">\(1\)</span>, or equivalently the larger <span class="math inline">\(x\)</span> is, the more likely the input is a <span class="math inline">\(1\)</span>. More on this in a future lesson.</p>
<p>To calculate the derivative of a function in sympy, use <code>y.diff(x)</code>, which means “differentiate <span class="math inline">\(y\)</span> with respect to <span class="math inline">\(x\)</span>”.</p>
<p>Here is a calculation of the derivative of the sigmoid function. I’ll also calculate the second derivative to show you how easy it is to do relative to the torture of trying to do it by hand.</p>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> sp.Symbol(<span class="st">'x'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> <span class="dv">1</span> <span class="op">/</span> (<span class="dv">1</span> <span class="op">+</span> sp.exp(<span class="op">-</span>x))</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>y.diff(x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<p><span class="math inline">\(\displaystyle \frac{e^{- x}}{\left(1 + e^{- x}\right)^{2}}\)</span></p>
</div>
</div>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>y.diff(x).diff(x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<p><span class="math inline">\(\displaystyle - \frac{e^{- x}}{\left(1 + e^{- x}\right)^{2}} + \frac{2 e^{- 2 x}}{\left(1 + e^{- x}\right)^{3}}\)</span></p>
</div>
</div>
</section>
</section>
<section id="integration" class="level1">
<h1>Integration</h1>
<p>Since integration is literally half of the subject of calculus, I owe it to at least briefly mention the topic. This section is only really applicable to the other topics in this book if you want to better understand probability distributions, something I’ll cover in detail in the next lesson. If you don’t mind thinking of probability distributions as histograms with infinitely many samples, you’re free to skip this section and move ahead.</p>
<section id="summing-infinitesimals" class="level2">
<h2 class="anchored" data-anchor-id="summing-infinitesimals">Summing Infinitesimals</h2>
<p>The other half of calculus is essentially about summing up small things to get big things. By small things of course I mean infinitesimals. Suppose we have a bunch of infinitesimals <span class="math inline">\(\varepsilon_0, \varepsilon_1, \cdots, \varepsilon_{n-1}\)</span>. We can add them together to get a new infinitesimal <span class="math inline">\(\varepsilon_0 + \varepsilon_1 + \cdots + \varepsilon_{n-1}\)</span>.</p>
<p>Suppose we want to add up the same infinitesimal <span class="math inline">\(\varepsilon\)</span> some number <span class="math inline">\(N\)</span> times, <span class="math display">\[\underbrace{\varepsilon + \varepsilon + \cdots + \varepsilon}_{\text{N times}} = N\varepsilon.\]</span></p>
<p>If <span class="math inline">\(N\)</span> is any reasonably sized finite number, say a number like <span class="math inline">\(N=1000\)</span>, then the product <span class="math inline">\(N\varepsilon\)</span> will again be infinitesimal, since <span class="math inline">\((N\varepsilon)^2 \approx 0\)</span>. But if we make <span class="math inline">\(N\)</span> <em>infinitely large</em>, then <span class="math inline">\(N\varepsilon\)</span> will be a finite number.</p>
<p>Here’s how this might look when adopting our informal convention that infinitesimals equal <span class="math inline">\(10^{-300}\)</span> and infinitely large numbers equal <span class="math inline">\(10^{300}\)</span>. For <span class="math inline">\(N=1000\)</span> the square <span class="math inline">\((N\varepsilon)^2 \approx 0\)</span>. But it’s not when we take <span class="math inline">\(N=10^{300}\)</span>. It’s finite, with <span class="math inline">\((N\varepsilon)^2=1\)</span>.</p>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>epsilon <span class="op">=</span> <span class="fl">1e-300</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>N <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>(N <span class="op">*</span> epsilon) <span class="op">**</span> <span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="17">
<pre><code>0.0</code></pre>
</div>
</div>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>N <span class="op">=</span> <span class="fl">1e300</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>(N <span class="op">*</span> epsilon) <span class="op">**</span> <span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="18">
<pre><code>1.0</code></pre>
</div>
</div>
<p>Thus, if we add up only a <em>finite</em> number of infinitesimals we’ll again get an <em>infinitesimal</em>. But, if we add up an <em>infinitely large</em> number of infinitesimals we’ll get something <em>finite</em>. This is the idea behind integration.</p>
</section>
<section id="area-under-the-curve" class="level2">
<h2 class="anchored" data-anchor-id="area-under-the-curve">Area Under The Curve</h2>
<p>Let’s do an example. Suppose we’re interested in calculating the area under the curve <span class="math inline">\(y=\sqrt{x}\)</span> between two points, say <span class="math inline">\(x=0\)</span> and <span class="math inline">\(x=10\)</span>. How would we go about this?</p>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>f <span class="op">=</span> <span class="kw">lambda</span> x: np.sqrt(x)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.linspace(<span class="dv">0</span>, <span class="dv">10</span>, <span class="dv">100</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>a, b <span class="op">=</span> <span class="dv">0</span>, <span class="dv">10</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>plot_function_with_area(x, f, a<span class="op">=</span>a, b<span class="op">=</span>b, title<span class="op">=</span><span class="st">'Area Under $y=\sqrt</span><span class="sc">{x}</span><span class="st">$ Between $0 \leq x \leq 10$'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="basic-calculus_files/figure-html/cell-20-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Perhaps the easiest idea is to approximate the function by a shape that’s easier to calculate the area of, something you’ve seen in geometry, like a square or a triangle. A better idea is to take a bunch of simple shapes, calculate their areas, and add them together.</p>
<p>Let’s try to do this using rectangles. Let’s approximate the function <span class="math inline">\(f(x)=\sqrt{x}\)</span> with <span class="math inline">\(N=10\)</span> equally-spaced rectangles of varying heights <span class="math inline">\(f(x)\)</span>, where <span class="math inline">\(x\)</span> is taken at each integer value <span class="math inline">\(x=1,2,3,\cdots,10\)</span>. The width of each rectangle is <span class="math inline">\(dx=\frac{b-a}{N}=1\)</span>. We know for rectangles their area is width times height, which in this case is <span class="math inline">\(dx \cdot f(x) = f(x)dx\)</span>. Then the total area under the curve of <span class="math inline">\(y=\sqrt{x}\)</span> would roughly be the sum of all these rectangle areas,</p>
<p><span class="math display">\[\begin{align}
A &amp;\approx f(1)dx + f(2)dx + f(3)dx + \cdots + f(10)dx \\
&amp;= \big(f(1) + f(2) + f(3) + \cdots + f(10)\big)\cdot dx \\
&amp;= \big(\sqrt{1} + \sqrt{2} + \sqrt{3} + \cdots + \sqrt{10}\big)\cdot 1 \\
&amp;\approx 22.468
\end{align}\]</span></p>
<p>It’s helpful to visualize what’s going on. I’ll plot this area approximation scheme by using the helper function <code>plot_approximating_rectangles</code>, which will show the plot of the curve and its approximating rectangles. It also prints out the approximating area calculated above.</p>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>plot_approximating_rectangles(x, f, dx<span class="op">=</span><span class="fl">1.0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Approximate Area: 22.468278186204103</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="basic-calculus_files/figure-html/cell-21-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>If you stare at the plot you can see our area estimate is okay but not great. The rectangles are <em>overestimating</em> the area under the curve since they all have segments of area lying above the curve.</p>
<p>The problem was that the rectangles we used were too coarse. It’s better to use narrower rectangles, and more of them. What we need to do is make <span class="math inline">\(dx\)</span> smaller by making <span class="math inline">\(N\)</span> bigger. Let’s try using <span class="math inline">\(N=50\)</span> rectangles of width <span class="math inline">\(dx=0.2\)</span> instead and see how much the result improves.</p>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>plot_approximating_rectangles(x, f, dx<span class="op">=</span><span class="fl">0.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Approximate Area: 21.380011968222313</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="basic-calculus_files/figure-html/cell-22-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>It looks better. We’re at <span class="math inline">\(21.380\)</span> now. If you zoom in you’ll see we’re still overestimating the true area, but not by near as much as before. As we make <span class="math inline">\(dx\)</span> smaller and smaller, and <span class="math inline">\(N\)</span> bigger and bigger, this estimate will get better and better.</p>
<p>The exact area under this curve turns out to be</p>
<p><span class="math display">\[A = \frac{20}{3}\sqrt{10} \approx 21.082.\]</span></p>
<p>This will be the case when the rectangles are infinitesimally thin, so thin that the errors disappear and the area calculation becomes exact.</p>
<p>Let’s try to calculate the approximating areas using smaller and smaller rectangles and see how close we can get to the exact answer. To do this, I’ll use a loop to calculate the area for successively smaller values of <span class="math inline">\(dx\)</span>.</p>
<div class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>f <span class="op">=</span> <span class="kw">lambda</span> x: np.sqrt(x)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> dx <span class="kw">in</span> [<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="fl">0.01</span>, <span class="fl">0.001</span>, <span class="fl">0.0001</span>]:</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>    N <span class="op">=</span> <span class="bu">int</span>(<span class="dv">10</span> <span class="op">/</span> dx)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>    xs <span class="op">=</span> np.cumsum(dx <span class="op">*</span> np.ones(N))</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>    area <span class="op">=</span> np.<span class="bu">sum</span>([f(x)<span class="op">*</span>dx <span class="cf">for</span> x <span class="kw">in</span> xs])</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'N = </span><span class="sc">{</span>N<span class="sc">:6d}</span><span class="ss"> </span><span class="ch">\t</span><span class="ss"> dx = </span><span class="sc">{</span>dx<span class="sc">:8.4f}</span><span class="ss"> </span><span class="ch">\t</span><span class="ss"> A = </span><span class="sc">{</span>area<span class="sc">:4f}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>N =     10   dx =   1.0000   A = 22.468278
N =    100   dx =   0.1000   A = 21.233523
N =   1000   dx =   0.0100   A = 21.097456
N =  10000   dx =   0.0010   A = 21.083426
N = 100000   dx =   0.0001   A = 21.082009</code></pre>
</div>
</div>
<p>It looks like if we want to get the correct answer <span class="math inline">\(21.082\)</span> to 3 decimal places we’d need to use <span class="math inline">\(N=100000\)</span> rectangles of width <span class="math inline">\(dx=10^{-4}\)</span>. In practice that’s an awful lot of terms to sum up. There are better ways to actually calculate these things numerically than just using the above definition (e.g.&nbsp;<a href="https://en.wikipedia.org/wiki/Simpson%27s_rule">Simpson’s Rule</a>), but I won’t go into those.</p>
<p>Let’s generalize this. Suppose we want to calculate the area under the curve of some function <span class="math inline">\(y=f(x)\)</span> between two points <span class="math inline">\(x=a\)</span> and <span class="math inline">\(x=b\)</span>. We can do this by taking <span class="math inline">\(N\)</span> rectangles each of width <span class="math inline">\(dx=\frac{b-a}{N}\)</span> and height <span class="math inline">\(f(x)dx\)</span> and summing up their areas. If <span class="math inline">\(x_0,x_1,\cdots,x_{N-1}\)</span> are the points we’re evaluating the heights at, then <span class="math display">\[A \approx f(x_0)dx + f(x_1)dx + f(x_2)dx + \cdots + f(x_{N-1})dx = \sum_{n=0}^{N-1} f(x_n) dx.\]</span></p>
<p>To get the exact area, let’s allow <span class="math inline">\(N\)</span> to get infinitely large, which also means <span class="math inline">\(dx\)</span> will become infinitesimal. When we do this, it’s conventional to use a different symbol for the sum, the long-S symbol <span class="math inline">\(\int\)</span>. Instead of writing</p>
<p><span class="math display">\[A = \sum_{n=0}^{N-1} f(x_n) dx,\]</span></p>
<p>we’d write <span class="math display">\[A = \int_a^{b} f(x) dx.\]</span></p>
<p>Read this as “the integral from 0 to 10 of <span class="math inline">\(f(x)dx\)</span>”. It’s called the <strong>definite integral</strong> of the function. In our example, this would be</p>
<p><span class="math display">\[A = \int_0^{10} \sqrt{x} dx.\]</span></p>
<p>Of course, this fancy notation doesn’t actually tell us anything new. We’re still just summing up the areas of a bunch of rectangles.</p>
</section>
<section id="integration-rules" class="level2">
<h2 class="anchored" data-anchor-id="integration-rules">Integration Rules</h2>
<p>It’s not at all clear from this definition how we’d get the <em>exact</em> answer <span class="math inline">\(A=\frac{20}{3}\sqrt{10}\)</span> shown above. We can get to it approximately by summing rectangle areas, but if we want to get the exact value we’ll need a few integral rules.</p>
<p>Before doing so I need to talk about the <strong>indefinite integral</strong>, sometimes called the antiderivative. If <span class="math inline">\(f(x)\)</span> is some function, then its indefinite integral is some other function <span class="math inline">\(F(x)\)</span> whose derivative is <span class="math inline">\(f(x)\)</span>, <span class="math display">\[f(x) = \frac{d}{dx} F(x).\]</span></p>
<p>Typically the indefinite integral is written as an integral, but without limits of integration shown,</p>
<p><span class="math display">\[F(x) = \int f(x) dx.\]</span></p>
<p>To evaluate a typical <em>definite</em> integral like <span class="math inline">\(\int_a^b f(x) dx\)</span> the rule is <span class="math display">\[\int_a^b f(x) dx = F(x) \bigg|_{x=a}^{x=b} = F(b) - F(a).\]</span></p>
<p>That is, we first calculate the indefinite integral <span class="math inline">\(F(x)\)</span>, then evaluate it at the points <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>, then subtract their difference to get the definite integral, which itself is just the area under the curve of <span class="math inline">\(f(x)\)</span>. The fact we can think of areas under curves in terms of another function like this is not obvious. It follows from the <strong>Fundamental Theorem of Calculus</strong>, which I won’t try to prove here.</p>
<p>With this out of the way, here are some common indefinite integrals. Note we can add a constant <span class="math inline">\(c\)</span> to each of these and the answer would still be the same. I’ll state them in the standard form where <span class="math inline">\(c=0\)</span>. | Common Integrals| | — | | <span class="math inline">\(\int 0 dx = 0\)</span> | | <span class="math inline">\(\int 1 dx = x\)</span> | | <span class="math inline">\(\int x dx = \frac{1}{2}x^2\)</span> | | <span class="math inline">\(\int x^2 dx = \frac{1}{3}x^3\)</span> | | <span class="math inline">\(\int \sqrt{x} dx = \frac{2}{3} x^{3/2}\)</span> | | <span class="math inline">\(\int \frac{1}{x} dx = \log{x}\)</span> | | <span class="math inline">\(\int e^x dx = e^x\)</span> | | <span class="math inline">\(\int \log{x} dx = x \log{x} - x\)</span> | | <span class="math inline">\(\int \sin{x} dx = -\cos{x}\)</span> | | <span class="math inline">\(\int \cos{x} dx = \sin{x}\)</span> |</p>
<p>Here are a few more general integral rules:</p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Name</th>
<th>Rule</th>
<th>Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fundamental Theorem of Calculus</td>
<td><span class="math inline">\(\int_a^b f(x) dx = F(b) - F(a)\)</span> where <span class="math inline">\(\frac{d}{dx}F(x) = f(x)\)</span></td>
<td><span class="math inline">\(\int_0^1 x dx = \frac{1}{2} x^2 \big |_0^1 = \frac{1}{2} 1^2 - \frac{1}{2} 0^2 = \frac{1}{2}\)</span></td>
</tr>
<tr class="even">
<td>Reversing Limits of Integration</td>
<td><span class="math inline">\(\int_b^a f(x) dx = -\int_a^b f(x) dx\)</span></td>
<td><span class="math inline">\(\int_2^0 1 dx = -\int_0^2 1 dx = 2\)</span></td>
</tr>
<tr class="odd">
<td>Splitting Up Limits of Integration</td>
<td><span class="math inline">\(\int_a^b f(x) dx = \int_a^c f(x) dx + \int_c^d f(x) dx\)</span></td>
<td><span class="math inline">\(\int_0^2 1 dx = \int_0^1 1 dx + \int_1^2 1 dx = 1 + (2-1) = 2\)</span></td>
</tr>
<tr class="even">
<td>Power Rule</td>
<td><span class="math inline">\(\int x^n dx = \frac{1}{n+1}x^{n+1}\)</span> for any <span class="math inline">\(n \neq -1\)</span></td>
<td><span class="math inline">\(\int x^{-2} dx = \frac{1}{-2+1}x^{-2+1} = -\frac{1}{x}\)</span></td>
</tr>
<tr class="odd">
<td>Addition Rule</td>
<td><span class="math inline">\(\int (u + v) dx = \int u dx + \int v dx\)</span></td>
<td><span class="math inline">\(\int (1 + e^x) dx = \int 1 dx + \int e^x dx = x + e^x\)</span></td>
</tr>
<tr class="even">
<td>Constant Rule</td>
<td><span class="math inline">\(\int cf(x) dx = c \int f(x) dx\)</span></td>
<td><span class="math inline">\(\int 5 \cos{x} dx = 5 \int \cos{x} dx = 5 \sin{x}\)</span></td>
</tr>
<tr class="odd">
<td>Integration By Parts</td>
<td><span class="math inline">\(\int u dv = uv - \int v du\)</span></td>
<td>$x e^x dx = x d(e^x) = x e^x - e^x dx = x e^x - e^x $</td>
</tr>
<tr class="even">
<td>Leibniz Rule</td>
<td><span class="math inline">\(\frac{d}{dx} \int f(x) dx = f(x)\)</span></td>
<td><span class="math inline">\(\frac{d}{dx} \int_0^x \sin t dt = \sin x\)</span></td>
</tr>
<tr class="odd">
<td>Change of Variables</td>
<td><span class="math inline">\(\int f(u) du = \int f(u(x)) \frac{du}{dx} dx\)</span></td>
<td><span class="math inline">\(\int x e^{x^2} dx = \int e^{x^2} d\big(\frac{1}{2}x^2\big) = \frac{1}{2} \int e^u du = \frac{1}{2} e^u = \frac{1}{2} e^{x^2}\)</span></td>
</tr>
</tbody>
</table>
<p>Note <span class="math inline">\(d(f(x))\)</span> is just the differential form of the derivative <span class="math inline">\(\frac{d}{dx}f(x)\)</span>, so <span class="math inline">\(d(f(x)) = \frac{d}{dx}f(x) dx\)</span>.</p>
<p>It’s worth mentioning that integral rules are often much harder to apply than derivative rules. In fact, it’s not even possible to symbolically integrate every function. The Gaussian function <span class="math inline">\(y=e^{-x^2}\)</span> is a well-known example of a function that can’t be integrated symbolically. Of course, we can <em>always</em> calculate the <em>definite</em> integral numerically, even if we can’t symbolically.</p>
<p>Just as with derivatives, sympy can evaluate integrals for you, both definite and indefinite integrals. Below I’ll use <code>y.integrate((x, 0, 10))</code> to calculate the area under the curve problem I did before,</p>
<p><span class="math display">\[A = \int_0^{10} \sqrt{x} dx = \frac{20}{3} \sqrt{10}.\]</span></p>
<div class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> sp.Symbol(<span class="st">'x'</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> sp.sqrt(x)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>y.integrate((x, <span class="dv">0</span>, <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<p><span class="math inline">\(\displaystyle \frac{20 \sqrt{10}}{3}\)</span></p>
</div>
</div>
<p>Sympy can of course handle indefinite integrals too by leaving off the limits of integration.</p>
<div class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>y.integrate(x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="24">
<p><span class="math inline">\(\displaystyle \frac{2 x^{\frac{3}{2}}}{3}\)</span></p>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation column-body">
  <div class="nav-page nav-page-previous">
      <a href="../notebooks/vectorization.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Arrays and Vectorization</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../notebooks/linear-systems.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Systems of Linear Equations</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>